trigger: none
pr: none

# Pipeline resource defined as per https://bit.ly/3PhwhRk
resources:
  pipelines:
  - pipeline: build_pipeline        # Used to reference the pipeline reference from other parts of the code.
    source: build_pipeline  	# This must match  the build pipeline name in ADO.
                                    # By default, pipelines are named after the ADO build pipeline name.
    trigger:
      branches:
      - master                      # Will get triggered whenever the source pipeline runs on master branch.

jobs:
- deployment: TestTemplate9_deploy_to_appservice
  displayName: TestTemplate9 Deploy to AppService
  environment: production
  variables:
    adoProject: 'TestTemplate9'
    azureServiceConnection: 'AzureConnection_TestTemplate9'
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
          fetchDepth: 0

        - script: pwd
          displayName: 'Basic Information - pwd'

        - script: ls -al
          displayName: 'Basic Information - Directory Contents'

        - task: PowerShell@2
          displayName: 'Create version number'
          name: 'CreateVersionNumber'
          inputs:
            targetType: 'inline'
            script: |
              $newVersion = "$(resources.pipeline.build_pipeline.runName)"
              [string] $buildName = "$($newVersion)"
              Write-Host "##vso[build.updatebuildnumber]$buildName"

        - download: none

        - task: DownloadPipelineArtifact@2
          displayName: 'Download Artifact TestTemplate9.Api'
          inputs:
            buildType: 'specific'
            definition: build_pipeline
            buildVersionToDownload: 'latest'
            artifactName: 'drop.TestTemplate9.Api'
            project: '$(adoProject)'
            downloadPath: '$(Pipeline.Workspace)/drop/TestTemplate9.Api'

        - task: DownloadPipelineArtifact@2
          displayName: 'Download Artifact TestTemplate9.WorkerServices'
          inputs:
            buildType: 'specific'
            definition: build_pipeline
            buildVersionToDownload: 'latest'
            artifactName: 'drop.TestTemplate9.WorkerServices'
            project: '$(adoProject)'
            downloadPath: '$(Pipeline.Workspace)/drop/TestTemplate9.WorkerServices'

        - task: DownloadPipelineArtifact@2
          displayName: 'Download Artifact TestTemplate9.Migrations'
          inputs:
            buildType: 'specific'
            definition: build_pipeline
            buildVersionToDownload: 'latest'
            artifactName: 'drop.TestTemplate9.Migrations'
            project: '$(adoProject)'
            downloadPath: '$(Pipeline.Workspace)/drop/TestTemplate9.Migrations'

        - task: AzureCLI@2
          displayName: 'Entra Api Registration'
          name: 'entraApiRegistration'
          inputs:
            azureSubscription: 'AzureConnection'
            scriptType: pscore
            scriptLocation: 'scriptPath'
            scriptPath: './deployment/entraApiRegistration.ps1'
            arguments: '$(PROJECT_NAME) $env:tenantId'
            powerShellErrorActionPreference: stop
        
        - task: AzureCLI@2
          displayName: 'Provision Resource Group'
          name: 'provisionResourceGroup'
          inputs:
            azureSubscription: 'AzureConnection'
            scriptType: pscore
            scriptLocation: 'scriptPath'
            scriptPath: './deployment/provisionResourceGroup.ps1'
            arguments: '$(LOCATION) $(ENVIRONMENT) $(PROJECT_NAME)'
            powerShellErrorActionPreference: stop

        - task: AzureCLI@2
          displayName: 'Sql Entra-Only Auth - Disable'
          name: 'SqlEntraOnlyAuthDisable'
          inputs:
            azureSubscription: 'AzureConnection'
            scriptType: pscore
            scriptLocation: 'scriptPath'
            scriptPath: './deployment/sqlEntraOnlyAuthDisable.ps1'
            arguments: '$(provisionResourceGroup.resourceGroupName)'
            powerShellErrorActionPreference: stop

        - task: AzureCLI@2
          displayName: 'Provision Resources'
          name: 'provisionResources'
          inputs:
            azureSubscription: 'AzureConnection'
            scriptType: pscore
            scriptLocation: 'scriptPath'
            scriptPath: './deployment/provisionResources.ps1'
            arguments: '$(ENVIRONMENT) $(PROJECT_NAME) $(provisionResourceGroup.resourceGroupName) $(SQL_ADMIN_USERNAME) $(SQL_ADMIN_PASSWORD) $(entraApiRegistration.authAuthority) $(entraApiRegistration.authAudience) $(entraApiRegistration.authValidIssuer)'
            powerShellErrorActionPreference: stop

        - task: AzureCLI@2
          displayName: 'Sql Entra Auth'
          name: 'SqlEntraAuth'
          inputs:
            azureSubscription: 'AzureConnection'
            scriptType: pscore
            scriptLocation: 'scriptPath'
            scriptPath: './deployment/sqlEntraAuth.ps1'
            arguments: '$(SQL_ADMINS_GROUP_NAME) $(SQL_ADMIN_USERNAME) $(SQL_ADMIN_PASSWORD) $(SQL_USERS_GROUP_NAME) $(provisionResourceGroup.resourceGroupName) $(provisionResources.appServiceWebName) $(provisionResources.sqlServerName)'
            powerShellErrorActionPreference: stop
            addSpnToEnvironment: true
            
        - task: AzureCLI@2
          displayName: 'Migrate database'
          name: 'migrateDatabase'
          inputs:
            azureSubscription: 'AzureConnection'
            scriptType: pscore
            scriptLocation: 'scriptPath'
            #inlineScript: 'dotnet $1 $2 $3 $4 $5'
            scriptPath: './deployment/migrate.ps1'
            arguments: '$(Pipeline.Workspace)/drop/TestTemplate9.Migrations/TestTemplate9.Migrations.dll "$(provisionResources.dbConnection)" $(SQL_ADMIN_USERNAME) $(SQL_ADMIN_PASSWORD) $(Pipeline.Workspace)/drop/TestTemplate9.Migrations'
            powerShellErrorActionPreference: stop
            
        #- script: dotnet $(Pipeline.Workspace)/drop/TestTemplate9.Migrations/TestTemplate9.Migrations.dll "$(provisionResources.dbConnection)" "$(SQL_ADMIN_USERNAME)" "$(SQL_ADMIN_PASSWORD)" "$(Pipeline.Workspace)/drop/TestTemplate9.Migrations"
        #  displayName: 'Migrate database'

        - task: AzureWebApp@1
          displayName: 'Deploy TestTemplate9.Api to App Service'
          inputs:
            azureSubscription: 'AzureConnection'
            appType: 'webAppLinux'
            appName: '$(provisionResources.appServiceWebName)'
            resourceGroupName: '$(provisionResourceGroup.resourceGroupName)'
            package: '$(Pipeline.Workspace)/drop/TestTemplate9.Api/**/*.zip'
            runtimeStack: 'DOTNETCORE|6.0'
